### ISSUE TITLE
Hover fails on json file containing only string

### ISSUE THREAD

**Issue by Levertion** [Microsoft/vscode-json-languageservice#25]
Steps for easiest reproduction:
 - open a new `vscode` editor
 - change format to JSON
 - insert `""`
 - move mouse over `""`

```
[Error - <TIME>] Error while computing hover for untitled:Untitled-1: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at JSONHover.doHover (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\node_modules\vscode-json-languageservice\lib\umd\services\jsonHover.js:35:28)
    at Object.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:318:55)
    at step (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:36:23)
    at Object.next (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:17:53)
    at c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:7:12)
    at c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\out\jsonServerMain.js:312:55
    at Immediate._onImmediate (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\out\utils\runner.js:28:20)
    at runCallback (timers.js:789:20)
```

The stack trace starts at https://github.com/Microsoft/vscode-json-languageservice/blob/99ef3f087b849f53a3d776e7701a0a10a07aa107/src/services/jsonHover.ts#L39.

A simple fix would be to change the `if` to:
```ts
if (parent && parent.type === 'property' && parent.keyNode === node) {...}
```
However, maybe it would be better to use a non-string node for properties keys anyway (I don't know this codebase, so maybe that's stupid).

**Comment by aeschli** [comment]
@Levertion Thanks for the issue.

**Comment by Levertion** [comment]
No problem, happy to help
